// Code generated by Gottani; see https://github.com/ktateish/gottani/. DO NOT EDIT.
package main

import (
	"bufio"
	"fmt"
	"os"
	"sort"
	"strconv"
)

//line lib/io/io.go:10
type Scanner struct {
	*bufio.Scanner
}

var scanner Scanner = Scanner{bufio.NewScanner(os.Stdin)}

func init() {
	scanner.Split(bufio.ScanWords)
}

func Next() string {
	if !scanner.Scan() {
		panic(scanner.Err())
	}
	return scanner.Text()
}

func NextInt() int {
	x, err := strconv.Atoi(Next())
	if err != nil {
		panic(err)
	}
	return x
}

func Println(a ...interface{}) {
	fmt.Println(a...)
}

func Print(a ...interface{}) {
	fmt.Print(a...)
}

//line main.go:8
func main() {
	n := NextInt()
	a := make([]int, n)
	for i := 0; i < n; i++ {
		a[i] = NextInt()
	}
	sort.Sort(sort.IntSlice(a))
	for i := 0; i < n; i++ {
		Print(a[i], " ")
	}
	Println()
}
